find_package(Git QUIET)
set(QTM_GIT_COMMIT "unknown")
if(Git_FOUND)
    execute_process(
        COMMAND "${GIT_EXECUTABLE}" rev-parse --short HEAD
        WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
        RESULT_VARIABLE QTM_GIT_RESULT
        OUTPUT_VARIABLE QTM_GIT_OUTPUT
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET
    )
    if(QTM_GIT_RESULT EQUAL 0 AND NOT QTM_GIT_OUTPUT STREQUAL "")
        set(QTM_GIT_COMMIT "${QTM_GIT_OUTPUT}")
    endif()
endif()

